language: java
sudo: false
before_install:
  - ./before_install.sh

after_success:
  - mvn clean cobertura:cobertura coveralls:report
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
matrix:
  allow_failures:
    - jdk: openjdk6
os:
  - linux
  - osx

